servAddr: 0.0.0.0:389
servUser: admin
servPass: mo7Ga775UdzKrpf4
debug: true
ldapConfig:
  - suffixDN:
    ldapURL:
    bindDN:
    bindPW:
    insecureSkipVerify:
    clientPoolSize: 10
    rewriteOrToAnd: true
    swapAttributeNameRule:
      - displayName<->description
    extraAttributes:
      - description
    excludeFilterKeys:
      -
